package logic

/* Test autogenerated with the tool go-test-gen. Created 2024-07-02 16:56:05 Tuesday */

import("testing")

func TestNewLexer(t *testing.T) {
	// todo implement 
}

func TestTokenize(t *testing.T) {
	// todo implement 
}

func TestString(t *testing.T) {
	// todo implement 
}
